version: '3'

volumes:
  db_data: {}
  server_static: {}

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DB_NAME='Whatsapp_API'
      - DB_USER='postgres'
      - DB_PASSWORD='1111'
      - DB_HOST='127.0.0.1'
      - DB_PORT=5432
    volumes:
      - .:/app:rw
      - server_static:/app/src/static:rw
    command: bash -c "python src/manage.py migrate && cd src && gunicorn config.wsgi:application --bind 0.0.0.0:8000"

  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB='Whatsapp_API'
      - POSTGRES_USER='postgres'
      - POSTGRES_PASSWORD='1111'
