version: "3"
volumes:
  db_data: {}
  server_static: {}

networks:
  my_network:
    driver: bridge

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.base
    env_file:
      - .env
    volumes:
      - .:/app:rw
      - server_static:/app/src/static:rw
    command: bash -c "python src/manage.py migrate && cd src && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    networks:
      - my_network

  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - my_network

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - server_static:/app/src/static:rw
    depends_on:
      - web
    networks:
      - my_network
