version: '3'

volumes:
  db_data: {}
  server_static: {}

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.base  
      - POSTGRES_DB=${NAME}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - DB_HOST=${HOST}
      - DB_PORT=${PORT}
      - JWT_SECRET_KEY: "SECRET_KEY"
      - JWT_ALGORITHM: "HS256"
      - JWT_EXPIRATION_DELTA: "timedelta(days=1)"
      - JWT_ALLOW_REFRESH: "True"
      - JWT_REFRESH_EXPIRATION_DELTA: "timedelta(days=7)"

    volumes:
      - .:/app:rw
      - server_static:/app/src/static:rw
    command: bash -c "python src/manage.py migrate && cd src && gunicorn config.wsgi:application --bind 0.0.0.0:8000"

  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${NAME}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
