# Generated by Django 4.2.2 on 2023-07-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='messages',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
